name: CICD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Replace the local URL to deployment URL in app.py
        run: sed -i 's|http://127.0.0.1:5000|https://bemyvalentine-v1.onrender.com|g' app.py

      - name: Replace the local URL to deployment URL in letter.html
        run: sed -i 's|http://127.0.0.1:5000|https://bemyvalentine-v1.onrender.com|g' templates/letter.html

      - name: Replace the local URL to deployment URL in sent_letter.html
        run: sed -i 's|http://127.0.0.1:5000|https://bemyvalentine-v1.onrender.com|g' templates/sent_letter.html

      - name: Debug Render API Response
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cuhbmfa3esus73ch3530/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"clearCache": false}' --verbose
      

